;******************************************************************************
;* @file    equ.inc part of gsi
;* @author  Glenn Self
;* @version V1.0
;* @date    April 2004
;* Copyright Glenn Self 2004
;******************************************************************************

;	radix <dec>

#ifndef EQU_INC_INCLUDED

#define EQU_INC_INCLUDED



TRUE	EQU	1
FALSE	EQU 	0


#endif ;EQU_INC_INCLUDED

