/*****************************************************************************
*	GSI a socket interface for Micro-controllers and Controller Area Network *
*   Copyright (C) 2014 Glenn Self                                            *
*                                                                            *
*   This program is free software: you can redistribute it and/or modify     *
*   it under the terms of the GNU General Public License as published by     *
*   the Free Software Foundation, either version 3 of the License, or        *
*   (at your option) any later version.                                      *
*                                                                            *
*    This program is distributed in the hope that it will be useful,         *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
*    GNU General Public License for more details.                            *
*                                                                            *
*    You should have received a copy of the GNU General Public License       *
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
// Name:        CloseNodeDialog.h
// Purpose:     
// Author:      Glenn Self
// Modified by: 
// Created:     03/04/2007 11:43:51
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 03/04/2007 11:43:51

#ifndef _CLOSENODEDIALOG_H_
#define _CLOSENODEDIALOG_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "CloseNodeDialog.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/valgen.h"
#include "wx/spinctrl.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define GSI_ID_CLIENT_TEST_CLOSE_NODE_DIALOG 10023
#define GSI_ID_CLIENT_TEST_SPINCTRL1 10024
#define SYMBOL_CLOSENODEDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_CLOSENODEDIALOG_TITLE _("CloseNodeDialog")
#define SYMBOL_CLOSENODEDIALOG_IDNAME GSI_ID_CLIENT_TEST_CLOSE_NODE_DIALOG
#define SYMBOL_CLOSENODEDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_CLOSENODEDIALOG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * CloseNodeDialog class declaration
 */

class CloseNodeDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( CloseNodeDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    CloseNodeDialog();
    CloseNodeDialog( wxWindow* parent, wxWindowID id = SYMBOL_CLOSENODEDIALOG_IDNAME, const wxString& caption = SYMBOL_CLOSENODEDIALOG_TITLE, const wxPoint& pos = SYMBOL_CLOSENODEDIALOG_POSITION, const wxSize& size = SYMBOL_CLOSENODEDIALOG_SIZE, long style = SYMBOL_CLOSENODEDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_CLOSENODEDIALOG_IDNAME, const wxString& caption = SYMBOL_CLOSENODEDIALOG_TITLE, const wxPoint& pos = SYMBOL_CLOSENODEDIALOG_POSITION, const wxSize& size = SYMBOL_CLOSENODEDIALOG_SIZE, long style = SYMBOL_CLOSENODEDIALOG_STYLE );

    /// Destructor
    ~CloseNodeDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin CloseNodeDialog event handler declarations

////@end CloseNodeDialog event handler declarations

////@begin CloseNodeDialog member function declarations

    int GetNode() const { return m_node ; }
    void SetNode(int value) { m_node = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end CloseNodeDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin CloseNodeDialog member variables
private:
    int m_node;
////@end CloseNodeDialog member variables
};

#endif
    // _CLOSENODEDIALOG_H_
