/*****************************************************************************
*	GSI a socket interface for Micro-controllers and Controller Area Network *
*   Copyright (C) 2014 Glenn Self                                            *
*                                                                            *
*   This program is free software: you can redistribute it and/or modify     *
*   it under the terms of the GNU General Public License as published by     *
*   the Free Software Foundation, either version 3 of the License, or        *
*   (at your option) any later version.                                      *
*                                                                            *
*    This program is distributed in the hope that it will be useful,         *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
*    GNU General Public License for more details.                            *
*                                                                            *
*    You should have received a copy of the GNU General Public License       *
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
// Name:        opensocketsession.h
// Purpose:
// Author:
// Modified by:
// Created:     27/02/2007 17:01:15
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 27/02/2007 17:01:15

#ifndef _OPENSOCKETSESSION_H_
#define _OPENSOCKETSESSION_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "opensocketsession.h"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/valtext.h"
#include "wx/valgen.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define GSI_ID_CLIENT_TEST_OPEN_SOCKET_SESSION 10017
#define GSI_ID_CLIENT_TEST_TEXTCTRL2 10019
#define GSI_ID_CLIENT_TEST_TEXTCTRL3 10018
#define SYMBOL_OPENSOCKETSESSION_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_OPENSOCKETSESSION_TITLE _("Open Socket session")
#define SYMBOL_OPENSOCKETSESSION_IDNAME GSI_ID_CLIENT_TEST_OPEN_SOCKET_SESSION
#define SYMBOL_OPENSOCKETSESSION_SIZE wxSize(400, 300)
#define SYMBOL_OPENSOCKETSESSION_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * OpenSocketsession class declaration
 */

class OpenSocketsession: public wxDialog
{
    DECLARE_DYNAMIC_CLASS( OpenSocketsession )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    OpenSocketsession();
    OpenSocketsession( wxWindow* parent, wxWindowID id = SYMBOL_OPENSOCKETSESSION_IDNAME, const wxString& caption = SYMBOL_OPENSOCKETSESSION_TITLE, const wxPoint& pos = SYMBOL_OPENSOCKETSESSION_POSITION, const wxSize& size = SYMBOL_OPENSOCKETSESSION_SIZE, long style = SYMBOL_OPENSOCKETSESSION_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_OPENSOCKETSESSION_IDNAME, const wxString& caption = SYMBOL_OPENSOCKETSESSION_TITLE, const wxPoint& pos = SYMBOL_OPENSOCKETSESSION_POSITION, const wxSize& size = SYMBOL_OPENSOCKETSESSION_SIZE, long style = SYMBOL_OPENSOCKETSESSION_STYLE );

    /// Destructor
    ~OpenSocketsession();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin OpenSocketsession event handler declarations

////@end OpenSocketsession event handler declarations

////@begin OpenSocketsession member function declarations

    wxString GetAddressString() const { return m_addressString ; }
    void SetAddressString(wxString value) { m_addressString = value ; }

    int GetAddressInt() const { return m_addressInt ; }
    void SetAddressInt(int value) { m_addressInt = value ; }

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end OpenSocketsession member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

private:
////@begin OpenSocketsession member variables
    wxTextCtrl* m_domain;
    wxTextCtrl* m_address;
private:
    wxString m_addressString;
    int m_addressInt;
////@end OpenSocketsession member variables


};

#endif
    // _OPENSOCKETSESSION_H_
