/*****************************************************************************
*	GSI a socket interface for Micro-controllers and Controller Area Network *
*   Copyright (C) 2014 Glenn Self                                            *
*                                                                            *
*   This program is free software: you can redistribute it and/or modify     *
*   it under the terms of the GNU General Public License as published by     *
*   the Free Software Foundation, either version 3 of the License, or        *
*   (at your option) any later version.                                      *
*                                                                            *
*    This program is distributed in the hope that it will be useful,         *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
*    GNU General Public License for more details.                            *
*                                                                            *
*    You should have received a copy of the GNU General Public License       *
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
// Name:        SetDeviceDialog.cpp
// Purpose:     
// Author:      Glenn Self
// Modified by: 
// Created:     12/03/2007 16:33:09
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 12/03/2007 16:33:09

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "SetDeviceDialog.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "SetDeviceDialog.h"

////@begin XPM images
////@end XPM images

/*!
 * SetDeviceDialog type definition
 */

IMPLEMENT_DYNAMIC_CLASS( SetDeviceDialog, wxDialog )

/*!
 * SetDeviceDialog event table definition
 */

BEGIN_EVENT_TABLE( SetDeviceDialog, wxDialog )

////@begin SetDeviceDialog event table entries
////@end SetDeviceDialog event table entries

END_EVENT_TABLE()

/*!
 * SetDeviceDialog constructors
 */

SetDeviceDialog::SetDeviceDialog()
{
    Init();
}

SetDeviceDialog::SetDeviceDialog( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * SetDeviceDialog creator
 */

bool SetDeviceDialog::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin SetDeviceDialog creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end SetDeviceDialog creation
    return true;
}

/*!
 * SetDeviceDialog destructor
 */

SetDeviceDialog::~SetDeviceDialog()
{
////@begin SetDeviceDialog destruction
////@end SetDeviceDialog destruction
}

/*!
 * Member initialisation 
 */

void SetDeviceDialog::Init()
{
////@begin SetDeviceDialog member initialisation
    m_Choice = NULL;
////@end SetDeviceDialog member initialisation
}
/*!
 * Control creation for SetDeviceDialog
 */

void SetDeviceDialog::CreateControls()
{    
////@begin SetDeviceDialog content construction
    // Generated by DialogBlocks, 17/06/2008 14:02:02 (Personal Edition)

    SetDeviceDialog* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    wxStaticBox* itemStaticBoxSizer3Static = new wxStaticBox(itemDialog1, wxID_ANY, _("Select device"));
    wxStaticBoxSizer* itemStaticBoxSizer3 = new wxStaticBoxSizer(itemStaticBoxSizer3Static, wxVERTICAL);
    itemBoxSizer2->Add(itemStaticBoxSizer3, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxArrayString m_ChoiceStrings;
    m_ChoiceStrings.Add(_("Com1"));
    m_ChoiceStrings.Add(_("Com2"));
    m_ChoiceStrings.Add(_("Com3"));
    m_ChoiceStrings.Add(_("Com4"));
    m_ChoiceStrings.Add(_("Com5"));
    m_ChoiceStrings.Add(_("Com6"));
    m_ChoiceStrings.Add(_("USB000"));
    m_ChoiceStrings.Add(_("USB001"));
    m_ChoiceStrings.Add(_("USB002"));
    m_ChoiceStrings.Add(_("USB003"));
    m_ChoiceStrings.Add(_("USB004"));
    m_ChoiceStrings.Add(_("USB005"));
    m_ChoiceStrings.Add(_("USB006"));
    m_ChoiceStrings.Add(_("USB007"));
    m_ChoiceStrings.Add(_("USB008"));
    m_ChoiceStrings.Add(_("USB009"));
    m_Choice = new wxChoice( itemDialog1, ID_LISTBOX1, wxDefaultPosition, wxDefaultSize, m_ChoiceStrings, 0 );
    m_Choice->SetStringSelection(_("Com1"));
    m_Choice->SetHelpText(_("Set a device name that hardware nodes are attached to."));
    if (SetDeviceDialog::ShowToolTips())
        m_Choice->SetToolTip(_("Set a device name that hardware nodes are attached to."));
    itemStaticBoxSizer3->Add(m_Choice, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer5 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer5, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxButton* itemButton6 = new wxButton( itemDialog1, wxID_OK, _("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer5->Add(itemButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton7 = new wxButton( itemDialog1, wxID_CANCEL, _("&Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer5->Add(itemButton7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end SetDeviceDialog content construction
}

/*!
 * Should we show tooltips?
 */

bool SetDeviceDialog::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap SetDeviceDialog::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin SetDeviceDialog bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end SetDeviceDialog bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon SetDeviceDialog::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin SetDeviceDialog icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end SetDeviceDialog icon retrieval
}
