
/*****************************************************************************
*	GSI a socket interface for Micro-controllers and Controller Area Network *
*   Copyright (C) 2014 Glenn Self                                            *
*                                                                            *
*   This program is free software: you can redistribute it and/or modify     *
*   it under the terms of the GNU General Public License as published by     *
*   the Free Software Foundation, either version 3 of the License, or        *
*   (at your option) any later version.                                      *
*                                                                            *
*    This program is distributed in the hope that it will be useful,         *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
*    GNU General Public License for more details.                            *
*                                                                            *
*    You should have received a copy of the GNU General Public License       *
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
// Name:        SetDeviceDialog.h
// Purpose:     
// Author:      Glenn Self
// Modified by: 
// Created:     12/03/2007 16:33:09
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 12/03/2007 16:33:09

#ifndef _SETDEVICEDIALOG_H_
#define _SETDEVICEDIALOG_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "SetDeviceDialog.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define GSI_ID_CLIENT_TEST_SETDEVICE_DIALOG 10021
#define ID_LISTBOX1 10022
#define SYMBOL_SETDEVICEDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_SETDEVICEDIALOG_TITLE _("Set device")
#define SYMBOL_SETDEVICEDIALOG_IDNAME GSI_ID_CLIENT_TEST_SETDEVICE_DIALOG
#define SYMBOL_SETDEVICEDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_SETDEVICEDIALOG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * SetDeviceDialog class declaration
 */

class SetDeviceDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( SetDeviceDialog )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    SetDeviceDialog();
    SetDeviceDialog( wxWindow* parent, wxWindowID id = SYMBOL_SETDEVICEDIALOG_IDNAME, const wxString& caption = SYMBOL_SETDEVICEDIALOG_TITLE, const wxPoint& pos = SYMBOL_SETDEVICEDIALOG_POSITION, const wxSize& size = SYMBOL_SETDEVICEDIALOG_SIZE, long style = SYMBOL_SETDEVICEDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_SETDEVICEDIALOG_IDNAME, const wxString& caption = SYMBOL_SETDEVICEDIALOG_TITLE, const wxPoint& pos = SYMBOL_SETDEVICEDIALOG_POSITION, const wxSize& size = SYMBOL_SETDEVICEDIALOG_SIZE, long style = SYMBOL_SETDEVICEDIALOG_STYLE );

    /// Destructor
    ~SetDeviceDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin SetDeviceDialog event handler declarations

////@end SetDeviceDialog event handler declarations

////@begin SetDeviceDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end SetDeviceDialog member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin SetDeviceDialog member variables
    wxChoice* m_Choice;
////@end SetDeviceDialog member variables
};

#endif
    // _SETDEVICEDIALOG_H_
