
/*****************************************************************************
*	GSI a socket interface for Micro-controllers and Controller Area Network *
*   Copyright (C) 2014 Glenn Self                                            *
*                                                                            *
*   This program is free software: you can redistribute it and/or modify     *
*   it under the terms of the GNU General Public License as published by     *
*   the Free Software Foundation, either version 3 of the License, or        *
*   (at your option) any later version.                                      *
*                                                                            *
*    This program is distributed in the hope that it will be useful,         *
*    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
*    GNU General Public License for more details.                            *
*                                                                            *
*    You should have received a copy of the GNU General Public License       *
*    along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
*****************************************************************************/
/////////////////////////////////////////////////////////////////////////////
// Name:        STLVolFreq.h
// Purpose:     
// Author:      Glenn Self
// Modified by: 
// Created:     30/03/2008 11:25:09
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 30/03/2008 11:25:09

#ifndef _STLVOLFREQ_H_
#define _STLVOLFREQ_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "STLVolFreq.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define STL_ID_VOL_FREQ_DIALOG 10013
#define STL_ID_CLIENT_TEST_SINE_VOL_CB 10030
#define STL_ID_CLIENT_TEST_SINE_FREQ_CB 10016
#define STL_ID_CLIENT_TEST_WN_VOL_CB 10100
#define STL_ID_CLIENT_TEST_CHAN_SC 10031
#define SYMBOL_STLSETVOLFREQDIALOG_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_STLSETVOLFREQDIALOG_TITLE _("Startle Set Volume/Frequency")
#define SYMBOL_STLSETVOLFREQDIALOG_IDNAME STL_ID_VOL_FREQ_DIALOG
#define SYMBOL_STLSETVOLFREQDIALOG_SIZE wxSize(400, 300)
#define SYMBOL_STLSETVOLFREQDIALOG_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * STLSetVolFreqDialog class declaration
 */

class STLSetVolFreqDialog: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( STLSetVolFreqDialog )
    //DECLARE_EVENT_TABLE()

public:
    /// Constructors
    STLSetVolFreqDialog();
    STLSetVolFreqDialog( wxWindow* parent, wxWindowID id = SYMBOL_STLSETVOLFREQDIALOG_IDNAME, const wxString& caption = SYMBOL_STLSETVOLFREQDIALOG_TITLE, const wxPoint& pos = SYMBOL_STLSETVOLFREQDIALOG_POSITION, const wxSize& size = SYMBOL_STLSETVOLFREQDIALOG_SIZE, long style = SYMBOL_STLSETVOLFREQDIALOG_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_STLSETVOLFREQDIALOG_IDNAME, const wxString& caption = SYMBOL_STLSETVOLFREQDIALOG_TITLE, const wxPoint& pos = SYMBOL_STLSETVOLFREQDIALOG_POSITION, const wxSize& size = SYMBOL_STLSETVOLFREQDIALOG_SIZE, long style = SYMBOL_STLSETVOLFREQDIALOG_STYLE );

    /// Destructor
    ~STLSetVolFreqDialog();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin STLSetVolFreqDialog event handler declarations

////@end STLSetVolFreqDialog event handler declarations

////@begin STLSetVolFreqDialog member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end STLSetVolFreqDialog member function declarations
//GS Additions
    /// Should we show tooltips?
    static bool ShowToolTips();
//Access functions
    wxComboBox* GetSineDBCB() const {return m_SineDB;}
    wxComboBox* GetSineFrequencyDBCB() const {return m_SineFrequency;}
    wxComboBox* GetNoiseDBCB()	const {return m_NoiseDB;}
	wxComboBox* GetChanCB() const {return m_Chan;}
	void	OnSetVolFreqCB ( wxCommandEvent& event);

private:
////@begin STLSetVolFreqDialog member variables
    wxComboBox* m_SineDB;
    wxComboBox* m_SineFrequency;
    wxComboBox* m_NoiseDB;
    wxComboBox* m_Chan;
////@end STLSetVolFreqDialog member variables
};

#endif
    // _STLVOLFREQ_H_
